### ISSUE TITLE
fit2gpx vs. Bryton

### ISSUE THREAD

**Issue by Dreamsthinker** [MaksVasilev/fit2gpx#1]
Добрый день.

Очень хорошая утилита, в т.ч. и тем, что распознает "нестандартные" .fit-файлы, записанные моим Bryton Rider 530.

В ходе обсуждения на [веломании](http://forum.velomania.ru/showthread.php?t=96384&page=421&p=6686653&viewfull=1#post6686653) (мой диалог с **pavlinux**) выяснилось, что по сути корректно их распознает только страва. Я заметил, что после обработки fit2gpx (без ошибок) получившийся .gpx выглядит несколько странно - одна и та же секунда повторяется по 2 раза с разными данными. А чуть позже на глаза попалась эта [тема](https://github.com/GoldenCheetah/GoldenCheetah/issues/2029).

GoldenCheetah анализирует этот .gpx криво, результаты абсолютно бесполезны. Имеющиеся решения не подходят - GPX/TCX из стравы получаются какими-то куцыми...

Проблему для себя я решил локально - написал на VBA )) маленький фикс, обрабатывающий .gpx. Он объединяет данные с одним и тем же временем и добавляет координаты в те точки, когда скорость равна 0 и работает Smart Pause.

Я не программист и понимаю, что мое "решение" работает только для моего набора (530+текущая прошивка+HR). Что будет с другими .fit от других пользователей Bryton - не представляю. На Bryton надежды нет - их support пребывает в зачаточном или предсмертном состоянии.

Поэтому, так как
> Любые предложения приветствуются!

я вношу свои: 1) добавить в fit2gpx функцию объединения данных из "record", имеющих "same timestamp", а также 2) добавить координаты и заодно elevation (и то, и другое из ближайшей из ранее записанных точек, где эти данные есть) в тех случаях, когда велосипед не движется и устройство переходит в режим паузы.

[Bryton.zip](https://github.com/MaksVasilev/fit2gpx/files/1203109/Bryton.zip)

**Comment by MaksVasilev** [comment]
Лучше вносить предложения в виде готовых пул-реквестов. Сейчас у меня нет времени на этот проект, вероятно я вернусь к нему с наступлением холодов.
