### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by alexg-k** [MaksVasilev/fit2gpx#2]
This just looks just like what I need.

Please translate your readme/issues also to English, so everybody can profit and contribute from your project.

Thanks!

**Comment by MaksVasilev** [comment]
Fix in dfcdf2b4977e7cb922101470688d633f3eef8097 24ff6af859addd118a59305a819c6c6689a2c348 97d5dbb88475985d62f907a54c84fd54ec516890 4af605770dc7b7a37187ea719d88ab4faba2e1dd
